// Duration days
const BASIC_DURATION_DAYS = 1;
const STANDARD_DURATION_DAYS = 2;
const PREMIUM_DURATION_DAYS = 3;
// Max listings
const BASIC_MAX_LISTINGS = 1;
const STANDARD_MAX_LISTINGS = 3;
const PREMIUM_MAX_LISTINGS = Infinity;
// Visibility
const BASIC_VISIBILITY = "standard";
const STANDARD_VISIBILITY = "enhanced";
const PREMIUM_VISIBILITY = "top-spot";
// Listing price
const BASIC_LISTING_PRICE = 300;
const STANDARD_LISTING_PRICE = 600;
const PREMIUM_LISTING_PRICE = 1200;

module.exports = {
  BASIC_DURATION_DAYS,
  STANDARD_DURATION_DAYS,
  PREMIUM_DURATION_DAYS,
  BASIC_MAX_LISTINGS,
  STANDARD_MAX_LISTINGS,
  PREMIUM_MAX_LISTINGS,
  BASIC_VISIBILITY,
  STANDARD_VISIBILITY,
  PREMIUM_VISIBILITY,
  BASIC_LISTING_PRICE,
  STANDARD_LISTING_PRICE,
  PREMIUM_LISTING_PRICE,
};
